# Generated by Django 5.0.7 on 2024-07-14 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitmentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.IntegerField(choices=[(0, 'Female'), (1, 'Male')])),
                ('education_level', models.IntegerField()),
                ('experience_years', models.IntegerField()),
                ('previous_companies', models.IntegerField()),
                ('distance_from_company', models.FloatField()),
                ('interview_score', models.IntegerField()),
                ('skill_score', models.IntegerField()),
                ('personality_score', models.IntegerField()),
                ('recruitment_strategy', models.IntegerField()),
            ],
        ),
    ]
