# Generated by Django 5.0.7 on 2024-07-31 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_recruitmentdata_education_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitmentdata',
            name='hire',
            field=models.IntegerField(choices=[(0, 'Not Hired'), (1, 'Hired')], default=1),
            preserve_default=False,
        ),
    ]
